#!/bin/sh

"[[PythonInstallation]]/scripts/pip.exe" install -t lib python-telegram-bot bs4 xmltodict six soundcloud feedparser requests tungsten mcstatus google-api-python-client
if [ -e "./lib/Scenic-Oxygen" ]; then
	git -C lib/Scenic-Oxygen pull
else
	git -C lib clone https://github.com/salamiarmy/Scenic-Oxygen
fi
cp -r -n "lib/Scenic-Oxygen/." ./
"[[GoogleCloudSDKInstallation]]/Google/Cloud SDK/google-cloud-sdk/bin/gcloud.cmd" app deploy app.yaml --project [[GoogleAppEngineProjectName]]
"[[PythonInstallation]]/python.exe" "[[GooglePythonAppEngineSDKInstallation]]/Google/google_appengine/appcfg.py" update_cron "./" --application [[GoogleAppEngineProjectName]]